# Generated by Django 3.2.13 on 2022-04-14 20:53

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(upload_to='images/')),
                ('sort_id', models.CharField(blank=True, max_length=30)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modify_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('created_by', models.CharField(blank=True, max_length=30)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modify_by', models.CharField(blank=True, max_length=30)),
                ('modify_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('configuration_key', models.CharField(blank=True, max_length=30)),
                ('configuration_value', models.CharField(blank=True, max_length=30)),
                ('created_by', models.CharField(blank=True, max_length=30)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modify_by', models.CharField(blank=True, max_length=30)),
                ('modify_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40)),
                ('email', models.CharField(blank=True, max_length=40)),
                ('message', models.CharField(blank=True, max_length=40)),
                ('subject', models.CharField(blank=True, max_length=40)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modify_by', models.CharField(blank=True, max_length=30)),
                ('modify_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=42)),
                ('percent_off', models.FloatField(blank=True, max_length=12.2)),
                ('no_of_uses', models.PositiveIntegerField(blank=True, max_length=30)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modify_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(blank=True, max_length=30)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shipping_method', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=25)),
                ('coupon_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.coupon')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.IntegerField(blank=True)),
                ('quantity', models.IntegerField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=30)),
                ('category', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('created_by', models.CharField(blank=True, max_length=30)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modify_by', models.CharField(blank=True, max_length=30)),
                ('modify_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributeValues',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute_value', models.CharField(blank=True, max_length=45)),
                ('created_by', models.CharField(blank=True, max_length=30)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modify_by', models.CharField(blank=True, max_length=30)),
                ('modify_date', models.DateField(auto_now_add=True)),
                ('product_attribute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.productattribute')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributesAssociate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.product')),
                ('product_attribute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.productattribute')),
                ('product_attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.productattributevalues')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, max_length=30)),
                ('total', models.DecimalField(decimal_places=2, max_digits=25)),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.order')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.product')),
            ],
        ),
    ]
