# Generated by Django 3.2.13 on 2022-04-14 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0003_cms_model_flatpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CMS_Model',
        ),
    ]
