# Generated by Django 3.2.13 on 2022-04-14 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flatpages', '0001_initial'),
        ('customadmin', '0004_delete_cms_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMS_Model',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.flatpage')),
                ('meta_title', models.TextField(blank=True, null=True)),
                ('meta_desc', models.TextField(blank=True, null=True)),
                ('meta_key', models.TextField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CMS_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CMS_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cms',
            },
            bases=('flatpages.flatpage',),
        ),
        migrations.DeleteModel(
            name='FlatPage',
        ),
    ]
